import type { AnalyzeResponse } from "./types";

export function buildMarkdownReport(report: AnalyzeResponse) {
  const findings = report.findings
    .map((f, i) => `### ${i + 1}. ${f.title}\n- Severity: ${f.severity}\n- Description: ${f.description}\n- Recommendation: ${f.recommendation}`)
    .join("\n\n");
  const checks = report.recommendedChecks.map((c) => `- ${c}`).join("\n");
  const signals = report.signals.map((s) => `- ${s}`).join("\n");

  return `# ChainGuard AI Risk Report\n\n- Chain: ${report.chain}\n- Address: ${report.address}\n- Address Type: ${report.addressType}\n- Risk Score: ${report.riskScore}/100\n- Risk Level: ${report.riskLevel}\n\n## Summary\n${report.summary}\n\n## Signals\n${signals || "- No signals collected"}\n\n## Findings\n${findings || "No findings detected."}\n\n## Recommended Manual Checks\n${checks}\n\n---\nGenerated by ChainGuard AI. This is a pre-audit signal report, not financial advice or a substitute for a professional security audit.\n`;
}
