import type { AnalyzeResponse } from "./types";

export function buildMarkdownReport(report: AnalyzeResponse) {
  const findings = report.findings
    .map((f, i) => {
      const evidence = f.evidence ? `\n- Evidence: ${f.evidence}` : "";
      const prompt = f.specialistPrompt ? `\n- Specialist prompt: ${f.specialistPrompt}` : "";
      return `### ${i + 1}. ${f.title}\n- Severity: ${f.severity}${evidence}\n- Description: ${f.description}\n- Recommendation: ${f.recommendation}${prompt}`;
    })
    .join("\n\n");
  const checks = report.recommendedChecks.map((c) => `- ${c}`).join("\n");
  const signals = report.signals.map((s) => `- ${s}`).join("\n");
  const sections = report.riskSections
    .map((section) => `### ${section.title}\n${section.items.map((item) => `- ${item}`).join("\n")}`)
    .join("\n\n");
  const social = report.socialReport;
  const market = report.marketReport;

  return `# ChainGuard AI Detailed Risk Report\n\n- Chain: ${report.chainName}\n- Address: ${report.address}\n- Address Type: ${report.addressType}\n- Scan Mode: ${report.scanMode}\n- Risk Score: ${report.riskScore}/100\n- Risk Level: ${report.riskLevel}\n- Social Trust Rating: ${social.score}/100 (${social.label})\n- Market Rating: ${market.score}/100 (${market.label})\n- Final Verdict: ${report.finalVerdict.label}\n\n## Executive Summary\n${report.executiveSummary}\n\n## Technical Summary\n${report.summary}\n\n## Final Verdict\n${report.finalVerdict.summary}\n\nRecommendation: ${report.finalVerdict.recommendation}\n\n## Social Media / Deployer Supporter Report\n${social.summary}\n\n### Positive Signals\n${social.positives.map((p) => `- ${p}`).join("\n")}\n\n### Warning Signals\n${social.warnings.map((w) => `- ${w}`).join("\n")}\n\n### Social Signals Checked\n${social.checkedSignals.map((s) => `- ${s}`).join("\n")}\n\n### Score Breakdown\n${social.scoreBreakdown.map((b) => `- ${b.points >= 0 ? "+" : ""}${b.points}: ${b.label} — ${b.reason}`).join("\n")}\n\n### Official Link / Metadata Comparison\n${social.metadataComparison.map((m) => `- ${m}`).join("\n")}\n\n### Social Manual Checks\n${social.manualChecks.map((m) => `- ${m}`).join("\n")}\n\n## Market / Liquidity Report\n${market.summary}\n\n### Market Verdict\n${market.verdict}\n\n### Positive Signals\n${market.positives.map((p) => `- ${p}`).join("\n")}\n\n### Warning Signals\n${market.warnings.map((w) => `- ${w}`).join("\n")}\n\n### Market Score Breakdown\n${market.scoreBreakdown.map((b) => `- ${b.points >= 0 ? "+" : ""}${b.points}: ${b.label} — ${b.reason}`).join("\n")}\n\n### Dex Pair Links\n${market.dexPairs.length ? market.dexPairs.map((u) => `- ${u}`).join("\n") : "- None provided"}\n\n### Market Manual Checks\n${market.manualChecks.map((m) => `- ${m}`).join("\n")}\n\n## Signals Collected\n${signals || "- No signals collected"}\n\n## Risk Domains Reviewed\n${sections}\n\n## Detailed Findings\n${findings || "No findings detected."}\n\n## Recommended Manual Checks\n${checks}\n\n## Analyst Notes\n- This is a pre-audit triage report.\n- Confirm all findings against verified source code and live on-chain data.\n- For meme/pump tokens, never rely on social volume alone; always verify authority, liquidity, holder concentration, and deployer behavior.\n\n---\nGenerated by ChainGuard AI. This is not financial advice or a substitute for a professional security audit.\n`;
}
